feat: crating toObjectChainReduce
codibre/fluent-iterable pull request #57
Opened 2023-03-04 09:12 UTC by Farenheith

toObjectChainReduce is similar to toObjectChain, with the difference that you have the freedom to define the leaf values. This is very useful because, as toObjectChain is a resolving operation, it'd be quite coding to iterate over the generated tree to access each leaf value and then transform it in what you want, if you don't want just to have an array with the values that matches that path.

2023-03-04 12:26 UTC, IcaroLettieri approved these changes, later dismissed

2023-03-08 00:26 UTC, DanielM08 requested changes

2023-03-08 00:26 UTC, DanielM08 commented on test/to-object-chain-reduce.spec.ts
> +    it('should return an array when no properties are informed', async () => {
Aqui não retornou um array, mas um número

2023-03-08 00:26 UTC, DanielM08 commented on test/to-object-chain-reduce.spec.ts
> +      it('should return an array when no properties are informed', () => {
Não retornou um array, mas um número

2023-03-08 00:26 UTC, DanielM08 commented on test/to-object-chain-reduce.spec.ts
> +      it('should create a object chain based on keyable informed properties', () => {
Thiago, poderia melhorar um pouco as asserções dos testes? por exemplo, porque não há valor para o acesso a 'a' na posição 2? e para 'd' na posição 1?

```
expect(result['a'][2])
expect(result['d'][1])
```

2023-03-08 00:26 UTC, DanielM08 commented on src/types/function-types/to-object-chain-function.ts
> +   * Creates an object chain with the values of the specified fields where the latest
Qual a vantagem disso? Qual um caso de uso?

2023-03-08 00:33 UTC, Farenheith commented on src/types/function-types/to-object-chain-function.ts
> +   * Creates an object chain with the values of the specified fields where the latest
Suponha que você vai precisar classificar um objeto por vários campos e só te interessa a soma dos campos dos quais te interessam:
```
fluent(list)
  .toObjectChainReduce(() => 0, (acc, profissional) => acc + profissional.horasTrabalhadas., 'idade', 'estado', 'profissao');
```
No exemplo acima consigo saber a quantidade de horas trabalhadas totais de profissionais por idade, estado e profissão que eu deseje consultar em O(1), após o objeto estar pronto.

É diferente deste comando:
```
fluent(list)
  .toObjectChain('idade', 'estado', 'profissao');
```

Nele, eu teria que acessar a chave desejada e somar, iterando sobre os itens, para ter o mesmo valor, porque ele não me dá autonomia para definir o tipo de objeto que estará nas folhas da árvore

2023-03-08 00:39 UTC, Farenheith commented on test/to-object-chain-reduce.spec.ts
> +      it('should create a object chain based on keyable informed properties', () => {
Não existem item tal qual test contenha a e c seja 2.
Para melhorar o asserton, fiz comparando o objet resultante inteiro.

2023-03-08 01:14 UTC, DanielM08 requested changes

2023-03-08 01:14 UTC, DanielM08 commented on test/to-object-chain-reduce.spec.ts
> +        expect(result).to.be.like({
O resultado da chave 'c' está sendo definida por especificação da chave 'c' como parâmetro do método, ou porque ela também é um dos valores do array da chave 'test'? 

Acho que vale a pena um novo caso de teste fazendo essa distinção, ou deixando mais claro isso nesse aqui, por exemplo, removendo o valor de 'c' do array de 'test' em um dos 3 objetos, ou adicionando um 3º valor para a chave 'c'

2023-03-08 10:27 UTC, Farenheith commented on test/to-object-chain-reduce.spec.ts
> +        expect(result).to.be.like({
alterei os valores das chaves para deixar mais claro

2023-03-08 12:48 UTC, DanielM08 approved these changes

2023-03-11 11:59 UTC, merged